tests:
  script:
    - pip3 install -r requirements.txt
    - py.test app/tests --cov=app
  tags:
    - docker

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy-dev:
  stage: deploy
  script:
    - docker build -t olympus.azurecr.io/lethe:latest .
    - docker login olympus.azurecr.io -u $AZURE_LOGIN -p $AZURE_PASS
    - docker push olympus.azurecr.io/lethe:latest
    - docker rmi olympus.azurecr.io/lethe:latest
    - docker logout olympus.azurecr.io
  environment: dev
  only:
    - master
  tags:
    - shell

deploy-staging:
  stage: deploy
  script:
    - docker build -t olympus.azurecr.io/lethe:staging .
    - docker login olympus.azurecr.io -u $AZURE_LOGIN -p $AZURE_PASS
    - docker push olympus.azurecr.io/lethe:staging
    - docker rmi olympus.azurecr.io/lethe:staging
    - docker logout olympus.azurecr.io
  environment: staging
  only:
    - staging
  tags:
    - shell

deploy-production:
  stage: deploy
  script:
    - docker build -t olympus.azurecr.io/lethe:production .
    - docker login olympus.azurecr.io -u $AZURE_LOGIN -p $AZURE_PASS
    - docker push olympus.azurecr.io/lethe:production
    - docker rmi olympus.azurecr.io/lethe:production
    - docker logout olympus.azurecr.io
  environment: production
  only:
    - production
  tags:
    - shell
