[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = false
lines_between_types = 1

[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
ignore_missing_imports = true
exclude = "lethe/tests/*"

[tool.pytest.ini_options]
testpaths = [
    "lethe/tests"
]

[tool.coverage.run]
omit = [
    "lethe/tests/*"
]
branch = true

[tool.coverage.report]
fail_under = 80